### ISSUE TITLE
Problème d'installation 

### ISSUE THREAD

**Issue by julientexier86** [erwang/dashboard_csv#2]
Bonjour pardon de déranger,
un brin newbie, j'ai tenter d'installer votre projet sur un espace perso (dans la perspective d'en avoir une copie fonctionnelle en plus de celui dispo sur votre site et le présenter aux collègues). 

Installé sur un serveur O2, après avoir exécuté "composer Install", le pointage du fichier index du dossier public renvoie une erreur 500. (500-server error). 

Une idée pour rendre cette belle application fonctionnelle ? 
Bien cordialement
Julien

**Comment by jourde** [comment]
Bonjour,

Merci pour votre message.
Je propose à Erwan d'y répondre, car c'est au-délà de mon domaine
d'expertise.

Cordialement,
François Jourde


Le ven. 3 juin 2022 à 12:06, julientexier86 ***@***.***> a
écrit :

**Comment by erwang** [comment]
Bonjour,
Normalement, tout devrait fonctionner sur votre serveur O2Switch.
Pouvez vous consulter les logs et me retourner le message d'erreur (normalement dans le dossier storage/logs).

**Comment by julientexier86** [comment]
Bonjour à vous deux,

Merci (de me répondre évidemment ^^) et pour votre travail qui va m’être très pratique et dont j’espère faire une promotion assez large auprès des collègues. 

Je crois que par force de bidouillage j’ai fini par comprendre d’où provenait le problème : il manquait à la racine le fichier .env qui était resté après composer en .env.example. Une fois le « .example » supprimé - ça fonctionne impeccablement ! (https://peda.lestexier.fr <https://peda.lestexier.fr/>)


Merci encore,

Julien


PS:Vous trouverez en PJ le log qui m’a en effet bien aidé!

**Comment by jourde** [comment]
Quel plaisir de voir une première installation du script!
Julien, quel est ton profil ? As-tu une page de présentation

Le dim. 5 juin 2022 à 17:11, julientexier86 ***@***.***> a
écrit :

> Bonjour à vous deux,
>
> Merci (de me répondre évidemment ^^) et pour votre travail qui va m’être
> très pratique et dont j’espère faire une promotion assez large auprès des
> collègues.
>
> Je crois que par force de bidouillage j’ai fini par comprendre d’où
> provenait le problème : il manquait à la racine le fichier .env qui était
> resté après composer en .env.example. Une fois le « .example » supprimé -
> ça fonctionne impeccablement ! (https://peda.lestexier.fr <
> https://peda.lestexier.fr/>)
>
>
> Merci encore,
>
> Julien
>
>
> PS:Vous trouverez en PJ le log qui m’a en effet bien aidé!
>
>
>
>
